### ISSUE TITLE
Handle ClojureScript files too

### ISSUE THREAD

**Issue by danielcompton** [benedekfazekas/mranderson#12]
There was a confusing bug for a user of refactor-nrepl, who was trying to specify his own version of tools.reader. refactor-nrepl uses mranderson for shading it's version of tools.reader, but mranderson doesn't handle ClojureScript files. These got copied in whole, and caused hard to debug issues. More details are available at https://github.com/technomancy/leiningen/issues/2097#issuecomment-186775194 and https://github.com/emezeske/lein-cljsbuild/issues/439.

**Comment by danielcompton** [comment]
@arichiardi, doesn't look like it would be too hard to make a patch for this to support cljs too https://github.com/benedekfazekas/mranderson/commit/70dbe9f5c809d1cbfea0f7feb6842fc1157c7a9e

**Comment by benedekfazekas** [comment]
thanks for letting me know! tbh (1) mranderson needs a rewrite (possibly from scratch) and (2) I am not sure if the thing mranderson does applies to cljs and if so how exactly. will check these issues out tho

**Comment by danielcompton** [comment]
Yeah, I'm not sure if it will actually work for CLJS, but it would be good to include CLJS files to get them out of harms way.

**Comment by arichiardi** [comment]
So just filtering them out?

**Comment by danielcompton** [comment]
No, copy them like mranderson does for `.clj` and `.cljc` files. They may or may not work, but they will at least be out of the way.

**Comment by benedekfazekas** [comment]
guys, having a bit of difficulty to prove that this is really good. also a bit reluctant to to build&upload a version of `refactor-nrepl` with snapshot mranderson to clojars. Any chance you can test this?

steps would be:

1.  get the version of `refactor-nrepl` you want to test with (I tested with HEAD master)
2. edit `project.clj` to use `thomasa/mranderson "0.4.7-SNAPSHOT"`
3. run `./build.sh install` to install `refactor-nrepl` locally (you need leiningen 2.6.0+) (takes looong)
4. make sure you use the newly built refactor-nrepl
5. test if the clash is fixed

**Comment by benedekfazekas** [comment]
actually latest refactor-nrepl 2.2.0-SNAPSHOT is built with fixed mranderson. let me know if it really fixes the problem. cc @danielcompton @arichiardi

**Comment by danielcompton** [comment]
Yep, this looks good, the cljs files are moved to `/mranderson047/toolsreader/v0v10v0_alpha3/cljs/tools/reader.cljs`.

**Comment by arichiardi** [comment]
A bit busy now but will test ASAP, and thanks, the code looks good.
