### ISSUE TITLE
Rewrites string literals

### ISSUE THREAD

**Issue by grammati** [benedekfazekas/mranderson#13]
I'm not sure if this behavior is intended or not, but mranderson rewrites string literals if they contain a full namespace name. This affects this line in cider-nrepl:

https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/refresh.clj#L32

The comment above indicates that the code in cider-nrepl was written this way (constructing a keyword at runtime) specifically so that this rewriting would not happen.

The result is that cider-refresh unloads and reloads namespaces that it should not.

**Comment by benedekfazekas** [comment]
just to clarify: I agree that `mranderson` having an effect on how the code is written in `cider-nrepl` is bad but this workaround actually solves

> The result is that cider-refresh unloads and reloads namespaces that it should not.

is that right?

**Comment by benedekfazekas** [comment]
apparently misunderstood the report initially. fix stops mranderson rewritting ns name if they are quoted as strings.
