### ISSUE TITLE
Maybe transition to using maintained fork of jarjar

### ISSUE THREAD

**Issue by RadicalZephyr** [benedekfazekas/mranderson#17]
It looks like the com.googlecode.jarjar has been abandoned these last six years.  Since then the pantsbuild developers have forked it for their own use at https://github.com/pantsbuild/jarjar

Their fork adds a few interesting features:
- a much newer version of ASM (6.2) (which is maintained)
- which adds support for working with Java 10 files (and many other improvements I'm sure)
- buffered jar writes (== better performance!)
- [improved (and configurable) handling of "misplaced class files"](https://github.com/pantsbuild/jarjar/commit/646f7f8d4b4fef7466e1a4f1246c60d90e013250)

Might be worth a look at using!  I may end up taking a look at updating it myself

**Comment by sogaiu** [comment]
There is also this: https://github.com/shevek/jarjar

Any idea how the two differ?

**Comment by jarohen** [comment]
https://github.com/pantsbuild/jarjar is now archived/read-only, https://github.com/shevek/jarjar came up top on Google when I searched for 'jarjar links' (although obviously not a conclusive metric :smile:)

(I did search first for 'jarjar' and had to refine my search, safe to say)

**Comment by lread** [comment]
There is also https://github.com/eed3si9n/jarjar-abrams
Not sure about the scala slant, but seems to be somewhat actively maintained?
