### ISSUE TITLE
Set metadata to identify inlined namespaces

### ISSUE THREAD

**Issue by martinklepsch** [benedekfazekas/mranderson#19]
Tools like https://cljdoc.org that generate API documentation will see inlined deps namespaces like any other namespace. This makes it hard to exclude namespaces from inlined dependencies from API documentation; making the API docs harder to read for end users.

It would be great of MrAnderson could attach some metadata to inlined namespaces so that those namespaces can be identified and excluded from API documentation. Perhaps just `:no-doc` is fine but something more MrAnderson specific would also be reasonable and useful enough. 

Here's an example of how this affects the [cider-nrepl API docs](https://cljdoc.org/d/cider/cider-nrepl/0.19.0-SNAPSHOT).

https://github.com/cljdoc/cljdoc/issues/195

**Comment by bbatsov** [comment]
It'd be nice if it also added something like `:inlined`, so tools could infer which namespaces are "private" vs "inlined".

**Comment by benedekfazekas** [comment]
by private you mean belonging to the the library not a dependency, or you mean something else?

**Comment by martinklepsch** [comment]
@benedekfazekas I think by "private" Bozhidar might refer to namespaces annotated with `:no-doc`. I think if you'd add something like`:mranderson/inlined-ns` to namespaces as metadata all requests would be accounted for. cljdoc would simply filter namespaces based on that and other users could easily identify "external" namespaces by checking if that key is present in the namespace's metadata.
