### ISSUE TITLE
shorten leiningen profile name `plugin.mranderson/config` 

### ISSUE THREAD

**Issue by benedekfazekas** [benedekfazekas/mranderson#23]

**Comment by benedekfazekas** [comment]
after thinking about this a bit I think I leave the above profile name alone. It is very easy to define an alias to shorten it the project file as such:
```clojure
:aliases {"mranderson"   ["with-profile" "+plugin.mranderson/config"]}
```

and then run
`lein mranderson test`

**Comment by bbatsov** [comment]
Fair enough. My main concern was that it wasn't consistent with the common naming patterns I've seen employed by another plugins.
