### ISSUE TITLE
Regression with Reagent macros in 0.5.0

### ISSUE THREAD

**Issue by danielcompton** [benedekfazekas/mranderson#28]
Previously, mranderson rewrote https://github.com/reagent-project/reagent/blob/master/src/reagent/debug.clj#L7 from

```cljs
(defmacro log
  "Print with console.log, if it exists."
  [& forms]
  `(when reagent.debug.has-console
     (.log js/console ~@forms)))

;; to

(defmacro log
  "Print with console.log, if it exists."
  [& forms]
  `(when mranderson048.reagent.v0v8v0.reagent.debug.has-console
     (.log js/console ~@forms)))
```

When using mranderson 0.5.0, the namespace form isn't rewritten, it stays exactly the same as the original.

Looking at the form, it is valid ClojureScript, though it may be more idiomatic to write `reagent.debug/has-console`.

I've noticed improvements elsewhere,  "Expected a reagent component, not "
 used to be rewritten to "Expected a mranderson048.reagent.v0v8v0.reagent component, not ", but is now left alone. I suspect this bug may be a side-effect of the change.

**Comment by benedekfazekas** [comment]
the latest `0.5.1-SNAPSHOT` on clojars is an alpha for `0.5.1` please check it out if it fixes this problem and works on your project

**Comment by danielcompton** [comment]
Yep, this works!
