### ISSUE TITLE
Namespace alias regression

### ISSUE THREAD

**Issue by liquidz** [benedekfazekas/mranderson#29]
### How to reproduce
project.clj
```
  :dependencies [[org.clojure/clojure "1.10.0"]
                 ^:source-dep [medley "1.1.0"]]
```

src/foo/core.clj
```clj
(ns foo.core
  (:require [medley.core :as medley]))

(defn foo []
  (medley/random-uuid))
```

In 0.4.9, `target/srcdeps/foo/core.clj` will be the following I expected.
```clj
(ns foo.core
  (:require [mranderson049.medley.v1v1v0.medley.core :as medley]))

(defn foo []
  (medley/random-uuid))
```

In 0.5.0, `medley` alias has changed and code is broken.
```clj
(ns foo.core
  (:require [mrandersonf85dac82.medley.v1v1v0.medley.core :as mrandersonf85dac82.medley.v1v1v0.medley]))

(defn foo []
  (medley/random-uuid))
```

**Comment by benedekfazekas** [comment]
thanks, will look into it. if you want to list your project in the projects using mranderson section in the readme, happy to take a PR

**Comment by bbatsov** [comment]
See https://github.com/liquidz/iced-nrepl It's pretty cool!

**Comment by benedekfazekas** [comment]
seen it yesterday, it is very cool

**Comment by liquidz** [comment]
@benedekfazekas @bbatsov Thanks!!

**Comment by benedekfazekas** [comment]
the latest `0.5.1-SNAPSHOT` on clojars is an alpha for `0.5.1` please check it out if it fixes this problem and works on your project

**Comment by liquidz** [comment]
@benedekfazekas I confirmed that this is fixed! Great thanks!!

**Comment by benedekfazekas** [comment]
is there anything else in your patchfile @liquidz I could take care of in MrAnderson?

**Comment by liquidz** [comment]
@benedekfazekas Nothing! Thanks!
