### ISSUE TITLE
Don't copy META-INF directories?

### ISSUE THREAD

**Issue by danielcompton** [benedekfazekas/mranderson#31]
In re-frame-10x we go through a bit of work to delete the META-INF directories and then delete any empty directory paths left over after that.

https://github.com/Day8/re-frame-10x/blob/40d9ff3ddf52d0469555fb3b7356d6dcb940fc58/source-deps.sh#L10-L16

Would it make sense to have an option to not copy those directories in, or is there some other reason why they are needed?

**Comment by benedekfazekas** [comment]
i don't think they are needed really

**Comment by benedekfazekas** [comment]
this should be fixed with the latest snapshot on clojars too

**Comment by danielcompton** [comment]
Yep, this works, thanks!
