### ISSUE TITLE
Fails to add prefix to Java classes compiled with Java >7

### ISSUE THREAD

**Issue by jarohen** [benedekfazekas/mranderson#48]
Hey @benedekfazekas :wave: 

repro:

* new project, `project.clj`:
  ```
  (defproject repro ""
    :dependencies [^:inline-dep [tech.droit/clj-diff "1.0.1"] ; example lib compiled with Java >7
                   ^:inline-dep [commons-codec "1.10"]] ; example lib compiled with Java <=7
    :plugins [[thomasa/mranderson "0.5.3"]])
  ```
* `lein inline-deps`
* `jar -tf target/class-deps.jar`

In the `class-deps.jar` file, we see the `org.apache.commons` classes correctly prefixed under `repro`, and the `clj_diff` class remaining unaltered - this unaltered class may well then clash with a different version included elsewhere.

This is caused by a check in `com.tonicsystems.jarjar.asm.ClassReader` from `com.googlecode.jarjar/jarjar:1.3`, which throws an `IllegalArgumentException` if the major number of the classfile is >51 - this exception is silently caught in `com.tonicsystems.jarjar.ext_util.JarTransformer`, and the class passes through the transformer unchanged.

Suspect that #17 is the solution to this (feel free to close this one) but wanted to write up this manifestation just in case it saves someone some time!

Cheers!

James

**Comment by benedekfazekas** [comment]
thanks for the exact repro steps and analysis @jarohen! -- @RadicalZephyr did submit a PR for this too but we hit some blockers when testing with `cider-nrepl`, see #18 for reference. I might have an other go on that branch/PR when I find some time.
