### ISSUE TITLE
Inconsistency with args pulled from project map vs CLI

### ISSUE THREAD

**Issue by jarohen** [benedekfazekas/mranderson#49]
In https://github.com/benedekfazekas/mranderson/blob/master/src/leiningen/inline_deps.clj#L16-L42, it seems that some of the options are pulled from the CLI, some from the project map, and some from both - is this intentional? 

Caught me out when I tried to include flags from the README in the project map :wink: 

If not, happy to write up a quick PR :)

James

**Comment by benedekfazekas** [comment]
if it does not work like how it is described (here)[https://github.com/benedekfazekas/mranderson#further-config-options] then it is not intentional. And even if it does I am happy to look at improvements ;)
