### ISSUE TITLE
intermitent broken files when inlining

### ISSUE THREAD

**Issue by benedekfazekas** [benedekfazekas/mranderson#56]
sometimes files in dependencies come out broken (part of the file is missing therefore parens are not closed). gut feeling is that something goes wrong when files are processed in parallel.

example
```
fazekasbenedek@scatha:~/projects/cider-nrepl (master)$ make test
lein with-profile -user inline-deps
project prefix:  cider.nrepl.inlined-deps
retrieve dependencies and munge clojure source files
in RESOLVED-TREE mode, working on a resolved dependency tree
 [cljfmt "0.8.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
   [com.googlecode.java-diff-utils/diffutils "1.3.0"]
   [org.clojure/tools.cli "1.0.206"]
   [rewrite-clj "1.0.605-alpha"]
 [org.clojure/tools.namespace "1.0.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "1.0.0"]
 [compliment "0.3.11" :exclusions [[org.clojure/clojure]]]
 [org.clojure/tools.trace "0.7.10" :exclusions [[org.clojure/clojure]]]
 [org.rksm/suitable "0.4.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
 [cider/orchard "0.7.1" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "1.1.0" :exclusions [[org.clojure/clojure]]]
 [org.clojure/tools.reader "1.3.2" :exclusions [[org.clojure/clojure]]]
 [fipp "0.6.24" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.rrb-vector "0.1.1"]
 [thunknyc/profile "0.5.2" :exclusions [[org.clojure/clojure]]]
 [mvxcvi/puget "1.3.1" :exclusions [[org.clojure/clojure]]]
   [mvxcvi/arrangement "1.2.0"]
unzipping [ orchard  [ v0v7v1 ]]
unzipping [ profile  [ v0v5v2 ]]
unzipping [ dynapath  [ v1v1v0 ]]
unzipping [ toolsnamespace  [ v1v0v0 ]]
unzipping [ cljfmt  [ v0v8v0 ]]
unzipping [ rewrite-clj  [ v1v0v605-alpha ]]
unzipping [ toolsreader  [ v1v3v2 ]]
unzipping [ suitable  [ v0v4v0 ]]
unzipping [ puget  [ v1v3v1 ]]
unzipping [ fipp  [ v0v6v24 ]]
unzipping [ corerrb-vector  [ v0v1v1 ]]
unzipping [ javaclasspath  [ v1v0v0 ]]
unzipping [ diffutils  [ v1v3v0 ]]
unzipping [ arrangement  [ v1v2v0 ]]
unzipping [ toolstrace  [ v0v7v10 ]]
unzipping [ toolscli  [ v1v0v206 ]]
unzipping [ compliment  [ v0v3v11 ]]
  munge source files of compliment artifact on branch [] exposed false.
  munge source files of toolscli artifact on branch [] exposed false.
  munge source files of toolstrace artifact on branch [] exposed false.
  munge source files of arrangement artifact on branch [] exposed false.
  munge source files of diffutils artifact on branch [] exposed false.
  munge source files of javaclasspath artifact on branch [] exposed false.
  munge source files of corerrb-vector artifact on branch [] exposed false.
  munge source files of fipp artifact on branch [] exposed false.
  munge source files of puget artifact on branch [] exposed false.
  munge source files of suitable artifact on branch [] exposed false.
  munge source files of toolsreader artifact on branch [] exposed false.
  munge source files of rewrite-clj artifact on branch [] exposed false.
  munge source files of cljfmt artifact on branch [] exposed false.
    prefixing imports in clojure files in 'target/srcdeps/cljfmt' ...
    prefixing imports: done
  munge source files of toolsnamespace artifact on branch [] exposed false.
  munge source files of dynapath artifact on branch [] exposed false.
  munge source files of profile artifact on branch [] exposed false.
  munge source files of orchard artifact on branch [] exposed false.
jaring all class file dependencies into target/class-deps.jar
prefixing #{"difflib"} in target/class-deps.jar with cidernrepl0270SNAPSHOT
deleting directories with class files in target/srcdeps...
   difflib  deleted
unzipping repackaged class-deps.jar into target/srcdeps
touch .inline-deps
lein with-profile -user,+1.10,+test,+plugin.mranderson/config test
Compiling 3 source files to /Users/fazekasbenedek/projects/cider-nrepl/target/classes
Syntax error reading source at (cider/nrepl/inlined_deps/toolsreader/v1v3v2/clojure/tools/reader/reader_types.clj:251:82).
Unmatched delimiter: ]
```

**Comment by vemv** [comment]
While I reckon that the reduced parallelism (#59) makes the issue less likely, probably we cannot assure it's gone in absence of a careful analysis.

Perhaps for the time being we can introduce an option (opt-in) to make all processing serial instead?

Sounds like a quick thing to PR.

Admittedly I wouldn't enjoy much using a slower mranderson, otoh I don't release every day, might even defer it to CI when I can.

**Comment by vemv** [comment]
> Perhaps for the time being we can introduce an option (opt-in) to make all processing serial instead?

WDYT?

**Comment by benedekfazekas** [comment]
an opt-in can't really hurt but not sure about the value of it, e.g. it may make mranderson unbearably slow even for CI jobs.  doing the same replacements in a bunch of files should be possible in parallel but then we should block until all the files are processed for one replacement round before the next round of processing can start. what/how is stuff going wrong needs a bit more hammock time at least for me.

**Comment by vemv** [comment]
I see!

Perhaps the flag can be a temporary (or undocumented) measure until the issue is fully debugged.

Cutting releases might be considered unfrequent enough to make slowness acceptable.

In contrast, from time to time I see mranderson failing in clojure-emacs CI matrixes. Normally it has no impact (I can re-run related test jobs). But if it happened when actually cutting a release, that could be pretty catastrophic.

**Comment by lread** [comment]
As of this writing, it seems the concurrency is at the file level:
https://github.com/benedekfazekas/mranderson/blob/f67a35b9991a498fe3a8c9487068bd563fd1d11b/src/mranderson/move.clj#L296-L299

So unless the same file is being processed at the same time more than once, there shouldn't be an clobbering issue. I can check on that possibility.

**Comment by lread** [comment]
That said, I do get intermittent failures  when canary testing refactor-nrepl against rewrite-clj on GitHub Actions. Here's one from today:
```
Compiling refactor-nrepl.inlined-deps.cljfmt.v0v8v0.cljfmt.main
Syntax error compiling at (refactor_nrepl/inlined_deps/version_clj/v1v0v0/version_clj/compare.cljc:105:5).
Unable to resolve symbol: s0 in this context
```
So yeah, there is probably something still amiss.
I'll try to trigger this locally on my dev box.

**Comment by lread** [comment]
Good news! In my tests, I am seeing that the list of files on which pmap operates is not always distinct, which would occasionally cause issues. I'll understand why and report back.

**Comment by benedekfazekas** [comment]
oh you mean inside one run, not as my theory went in [on 7 Dec 2021](https://github.com/benedekfazekas/mranderson/issues/56#issuecomment-987862779). interesting... mranderson may want to do different things in the same file or just a simple duplications which should be easy to get rid of, I wonder which.

**Comment by lread** [comment]
## Exploration
I've been testing with cider-nrepl.

I see the same files being processed 4 times under `clojure/tools`.
And the same files being processed 2 times under `compliment`

I've noticed that there is a utility fn `remove-subdirs` but I don't see anywhere that removes dupe dirs.

I'm not sure how MrAnderson is in the situation where there are dupe dirs for `compliment`, but for `clojure/tools` there are several libs that share this same root path, so that makes sense.

## Proposal
1. also remove duplicate dirs
1. throw an internal error if we detect duplicate files before invoking pmap (or map for that matter) processing.

**Comment by lread** [comment]
Hmmm... there's something else going on that I don't understand yet.

I'll try to figure out why `compliment` is being processed twice before creating a PR.

**Comment by lread** [comment]
Ok, seems like when we are processing an artifact, and its source dirs overlap with our current parent dirs we don't exclude the duplication. This means that we'll process the files twice.

I think my proposal above makes sense.
I will also make anything that returns a list of files non-lazy. 
The lazyness had me confused for a bit when debugging.

**Comment by benedekfazekas** [comment]
so do you (and @vemv ?) think that running tasks in parallel made this bug worse or rather made it show its head and there is probably no essential problem with parallel running? -- is this a wrong assumption somehow?
