### ISSUE TITLE
Consider Bumping Deps

### ISSUE THREAD

**Issue by lread** [benedekfazekas/mranderson#66]
## Currently
If I run antq:

```
clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version "RELEASE"} org.clojure/clojure {:mvn/version "1.11.1"}}}' -M -m antq.core
```
on MrAnderson, it reports:

|                         :name |      :current |   :latest |
|-------------------------------|---------------|-----------|
|      com.cemerick/pomegranate |         0.4.0 |     1.1.0 |
|               jonase/eastwood |         0.9.9 |     1.3.0 |
|           lambdaisland/kaocha |       0.0-418 | 1.69.1069 |
| lambdaisland/kaocha-cloverage |        0.0-32 |    1.0.75 |
| leiningen-core/leiningen-core |         2.9.1 |    2.9.10 |
|           org.clojure/clojure |        1.10.3 |    1.11.1 |
|   org.clojure/tools.namespace |         1.1.0 |     1.3.0 |
|       rewrite-clj/rewrite-clj | 1.0.682-alpha |    1.1.45 |

## I wonder
If we should consider upgrading some of these old deps?

Pros:
- I find a project easier to maintain when it uses current deps, you get to refer to current docs and get better support from library authors
- Might pick up improvements, fixes, and security updates
- Helps the Clojure community in that we are involved in using/testing current versions of libs

Cons:
- There's the entirely valid argument: if it isn't broken do not touch it
- Might pick up breakages

## Notes
- I did run [nvd-clojure](https://github.com/rm-hull/nvd-clojure) against MrAnderson, it found security issues in MrAnderson's transitive deps
- `com.cemerick/pomegranate` is now under [clj-commons/pomegranate](https://github.com/clj-commons/pomegranate)
- not listed above, but:
  - `me.raynes/fs` is now under the [clj-commons/fs](https://github.com/clj-commons/fs). Frankly, I would recommend a switch to [babashka/fs](https://github.com/babashka/fs) instead as it has a nice API and is under active development, but that would be a switch not a bump.
  - [org.pantsbuilt/jarjar](https://github.com/pantsbuild/jarjar) is no longer maintained, should we explore [jajar-abrams](https://github.com/eed3si9n/jarjar-abrams)?
- I can vouch for rewrite-clj! (I'm the primary maintainer on that project)
- kaocha and eastwood libs are a safe bet since we only use them for testing/linting

## Next steps
Lemme know how you feel, if any of this is interesting to you, I am happy to tackle this work.

**Comment by benedekfazekas** [comment]
I am deffo not against this specially quite a few deps are very out of date but not really a high prio unless a dated dep stops you (us ;) ) progressing with something interesting. Security issues are also concerning that said mranderson hopefully is never part of the application's runtime it works with so maybe that is not a big concern here.

not against switching to moved projects or to babashka/js for that matter. maybe I would jarjar alone -- it was updated relatively lately I think...

thx for the work on rewrite-clj btw it enables a really exciting ecosystem of projects :bow:

**Comment by lread** [comment]
Thanks for the reply, much appreciated!

If you don't object, I'll likely go ahead with the bumps.
When something goes wrong it is nice to not wonder if the problem is due to an old dep with a long-ago fixed issue.

And the security issues, while perhaps not a direct concern for MrAnderson, probably should be addressed, if just for optics.

I'll not switch to babashka/fs nor touch jarjar with my changes.
