### ISSUE TITLE
Consider CI Testing on Windows?

### ISSUE THREAD

**Issue by lread** [benedekfazekas/mranderson#75]
## Currently
MrAnderson CI testing is on Linux only.

## But...
I'm not sure if MrAnderson wants to be sure to be compatible with Windows

## If that's the case
We should probably add automated Windows CI testing.
This has helped me, on my projects anyway, to find issues I would have otherwise missed for Windows.

## Otherwise...
If Windows is not an important platform for MrAnderson, that's OK too.
We can close this issue if that's the case.

**Comment by benedekfazekas** [comment]
I don't think windows is important for mranderson, but happy to listen to a win case (pun intended -- sorry)

**Comment by lread** [comment]
Ha! Love a pun!

My only argument to support Windows for my projects is that Windows support is often 2nd class or an afterthought in the Clojure world. And that makes me feel sad for Windows users.

But... I think is it also perfectly acceptable to not take on the extra burden of explicitly supporting Windows. It's not like we get paid big bucks for this open source work, right? 🙂 

Would you be open to a little blurb on supported OSes in the README? Maybe something like:

> MrAnderson is supported and tested on Linux and should also work fine on macOS.

**Comment by benedekfazekas** [comment]
yeah the README addition defo makes sense. will do. I would say that mranderson is really a niche project so maybe windows support would not really worth even the minimal time/energy invested.

**Comment by lread** [comment]
Yeah, true. It could be more me crusading for the underdog.
But that underdog might never use MrAnderson in the first place!

Thanks for the discussion and please feel free to close this issue.

**Comment by benedekfazekas** [comment]
will close shortly, just keep it open so i don't forget the readme update ;)

**Comment by vemv** [comment]
I'd like to add that mranderson is best run from a CI machine, since the best practice nowadays is not to cut releases from one's laptop.

And it's pretty safe to assume that that CI machine will be unixy.

**Comment by lread** [comment]
Thanks @benedekfazekas, a side benefit: this makes is clearer for MrAnderson contributors too!
It makes it clear that we don't have to worry about differences like path and file separators or newlines. 👍
