### ISSUE TITLE
Watermarking inlined namespaces is a bit off

### ISSUE THREAD

**Issue by lread** [benedekfazekas/mranderson#78]
## Symptom

As part of #65, while previewing what MrAnderson would look like on cljdoc, I noticed that inlined namespace `mranderson.inlined.pomegranate.v1v2v1.cemerick.pomegranate.aether` was included in the docs.

MrAnderson uses the term "watermark" to describe adding `:mranderson/inlined` metadata to inlined namespaces. Cljdoc was just recently updated to treat this metadata the same way it does `:no-doc` metadata; it excludes the namespace.

So we should not see inlined namespaces in cljdoc api docs.

## Repro
I built MrAnderson locally with inlined namespaces via tweaked Makefile from #69 `make install`, which effectively does this:
```Shell
$ lein clean
$ lein with-profile -user,-dev install
$ lein with-profile -user,-dev,+mranderson-plugin inline-deps :skip-javaclass-repackage true
```

### A Look at Generated Inlined Namespaces
If I look at the inlined namespace:
```Shell
$ head target/srcdeps/mranderson/inlined/pomegranate/v1v2v1/cemerick/pomegranate/aether.clj
```
```Clojure
(ns mranderson.inlined.pomegranate.v1v2v1.cemerick.pomegranate.aether
  (:refer-clojure :exclude  [type proxy])
  (:require [clojure.java.io :as io]
            clojure.set
            [clojure.string :as str]
            clojure.stacktrace)
  (:import (org.eclipse.aether RepositorySystem)
           (org.eclipse.aether.transport.wagon WagonTransporterFactory
                                               WagonProvider)
           (org.eclipse.aether.transport.file FileTransporterFactory)

```
We can see that it is missing the `:mranderson/inlined` metadata.

An example of another inlined namespace shows the expected metadata:
```Shell
$ head -3 target/srcdeps/mranderson/inlined/rewrite_clj/v1v1v45/rewrite_clj/zip/walk.cljc 
```
```Clojure
(ns ^{:mranderson/inlined true} mranderson.inlined.rewrite-clj.v1v1v45.rewrite-clj.zip.walk
  (:require  [mranderson.inlined.rewrite-clj.v1v1v45.rewrite-clj.zip.move :as m]
             [mranderson.inlined.rewrite-clj.v1v1v45.rewrite-clj.zip.subedit :as subedit]))
```

### A First Look at Debugging
If I add some println debugging, I can see some odd stuff going on.

The watermark metadata is added to the aether namespace before it is inlined.
It is then removed after the aether namespace is inlined.

Which doesn't make a ton of sense.

## Next Steps
I'll dig deeper to see what's up and follow up with a fix.

**Comment by lread** [comment]
Ok, I'm thinking that maybe the current code is a bit wonky.

When processing the `ns` form:
- When a namespace name is renamed it loses all existing metadata regardless of whether or not the watermark is specified.
- When the namespace name is not renamed and a watermark is specified, then that watermark is added to the namespace name metadata.

Because aether was the last namespace name to be renamed, it didn't have the next loop of processing to partially compensate for the flaw.

Seems to me that the watermark processing should be dealt with only once: when inlining the namespace. 

I'll follow up with a PR sometime soon that will:
- preserve any existing metadata on an existing namespace 
- always add mranderson watermark metadata to inlined namespaces

**Comment by benedekfazekas** [comment]
that sounds really good. I noticed the problem too when working on the instaparse problems with tests authored by @r0man
